### ISSUE TITLE
Using both "borderColor" and "float: center" props results in an alignment issue

### ISSUE THREAD

**Issue by matchai** [sindresorhus/ink-box#1]
When using ink-box with a `borderColor` prop and `float: center`, vertical alignment of the box breaks, as is shown in the following screenshot.

Above: boxen
Below: ink-box
![image](https://user-images.githubusercontent.com/4658208/39830730-4969a08e-5390-11e8-8747-5c7ed7775362.png)

Below is the sample code that was used to produce this output:
```javascript
import { h, render } from 'ink';
import Box from 'ink-box';
import boxen from 'boxen';

console.log(
    boxen('Unicorns', { borderColor: 'cyan', float: 'center'})
);

render(
    <div>
        <Box borderColor="cyan" float="center">Unicorns</Box>
    </div>
);

```

**Update:**
Further investigation shows it to be the way `float: center` handles centering in ink.

The following snippet produces the same error:
```javascript
import { render } from 'ink';
import boxen from 'boxen';

render(boxen('Unicorns', { borderColor: 'cyan', float: 'center' }));
```

**Comment by sindresorhus** [comment]
Use the `Box` component in Ink instead.
