### ISSUE TITLE
Emoji causes misalignment

### ISSUE THREAD

**Issue by tomsun** [sindresorhus/ink-box#2]
Example:
```
<Box float="center" padding={1}>
  This is not quite right 🙅
</Box>
```

I.e. using:
https://emojipedia.org/face-with-no-good-gesture/

Output:

<img width="301" alt="ink-box-mbemoji" src="https://user-images.githubusercontent.com/442510/43516309-e4f908ca-958d-11e8-8e56-bf51e1b9d572.png">

(in macOS Terminal.app,  PT Mono 12pt)

**Comment by sindresorhus** [comment]
Use the `Box` component in Ink instead.
