### ISSUE TITLE
Box within ink-box causes issues

### ISSUE THREAD

**Issue by chrisdrackett** [sindresorhus/ink-box#5]
I'm trying to put an ink `Box` within a `Box` from `ink-box` and I'm getting two boxes as output.

the following code is what I'm trying to use:

```jsx
  <BorderBox borderStyle="round" borderColor="red" margin={1}>
    <Box flexDirection="column" justifyContent="center" alignItems="center">
      <Color red>Error</Color>
      <Box margin={1}>Error Text</Box>
    </Box>
  </BorderBox>
```

The output I get:

```
   ╭─────╮
   │Error│
   ╰─────╯



   ╭──────────╮
   │Error Text│
   ╰──────────╯
```

The output I expected:

```
   ╭────────────╮
   │Error       │
   |            |
   | Error Text |
   ╰────────────╯
```

**Comment by sindresorhus** [comment]
The plan is too absorb the functionality of `ink-box` into Ink.

**Comment by sindresorhus** [comment]
// @vadimdemedes

**Comment by sarmong** [comment]
@sindresorhus Will this be implemented any time soon? Or is there a workaround?

**Comment by sindresorhus** [comment]
@vadimdemedes Maybe we should open an issue on Ink about moving this to Ink so someone could help out getting it done?

**Comment by vadimdemedes** [comment]
Ink 3 adds support for everything that `ink-box` has to offer to the built-in `<Box>` component now :) See https://github.com/vadimdemedes/ink#borders.
